### ISSUE TITLE
Can't import bookmark file

### ISSUE THREAD

**Issue by dvdbng** [mapsme/omim#10965]
When importing a large (33MB) kml file, the import fails without any message. There is this error in logcat:
```
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at com.mapswithme.maps.intent.Factory$KmzKmlProcessor.getExtensionFromMime(Factory.java:578)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at com.mapswithme.maps.intent.Factory$KmzKmlProcessor.readKmzFromIntent(Factory.java:528)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at com.mapswithme.maps.intent.Factory$KmzKmlProcessor.lambda$process$0(Factory.java:508)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at com.mapswithme.maps.intent.-$$Lambda$Factory$KmzKmlProcessor$JztLktDLulo5ZZF3E7APf6V5L2c.run(Unknown Source:2)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor:       at java.lang.Thread.run(Thread.java:764)
05-28 22:51:54.790 27675 27842 W KmzKmlProcessor: Can't get bookmarks file from URI: content://media/external/file/460
```

I'm using [Simple file manager](https://f-droid.org/en/packages/com.simplemobiletools.filemanager.pro/) to open the file in a SM-G930F with a custom rom. Using the samsung stock file browser can't find apps to open the file.

**Comment by dvdbng** [comment]
Using [Dir](https://f-droid.org/en/packages/com.veniosg.dir/) it works
