### ISSUE TITLE
Crash when location enabled

### ISSUE THREAD

**Issue by CorentinCAM** [mapsme/omim#11097]
When I start the app with location enabled in my device, or when I turn on the location while the app is active, it instantly crashes.

Here is the trace from `adb logcat`:
```06-22 11:44:58.219  2036  2051 D GmsLocManagerSvcImpl: requestLocationSettingsDialog: com.google.android.gms.location.LocationSettingsRequest@1de3933
06-22 11:44:58.219  2036  2051 D GmsLocManagerSvcImpl: requestLocationSettingsDialog: com.google.android.gms.location.LocationSettingsRequest@1de3933
06-22 11:44:58.224  9667  9667 D AndroidRuntime: Shutting down VM
06-22 11:44:58.226  9667  9667 E AndroidRuntime: FATAL EXCEPTION: main
06-22 11:44:58.226  9667  9667 E AndroidRuntime: Process: com.mapswithme.maps.pro, PID: 9667
06-22 11:44:58.226  9667  9667 E AndroidRuntime: java.lang.SecurityException: UID [10158] is not related to packageName [com.mapswithme.maps.pro]
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2013)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1959)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.internal.zzeu.zzb(Unknown Source:10)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.internal.zzcfa.zza(Unknown Source:15)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.internal.zzcfk.zza(Unknown Source:35)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.internal.zzcfw.zza(Unknown Source:6)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzm.zzb(Unknown Source:8)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzal.zze(Unknown Source:69)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzal.zzd(Unknown Source:0)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzbi.zzd(Unknown Source:5)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzba.zzd(Unknown Source:98)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.internal.zzcfv.checkLocationSettings(Unknown Source:6)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.mapswithme.maps.location.GoogleFusedLocationProvider.checkSettingsAndRequestUpdates(GoogleFusedLocationProvider.java:89)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.mapswithme.maps.location.GoogleFusedLocationProvider.onConnected(GoogleFusedLocationProvider.java:81)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzae.zzk(Unknown Source:113)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzba.zzj(Unknown Source:22)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzao.zzaie(Unknown Source:90)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzao.onConnected(Unknown Source:21)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzbi.onConnected(Unknown Source:7)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzt.onConnected(Unknown Source:5)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzac.onConnected(Unknown Source:2)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzn.zzakr(Unknown Source:130)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zze.zzw(Unknown Source:62)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzi.zzaks(Unknown Source:51)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source:270)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
06-22 11:44:58.226  9667  9667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
06-22 11:44:58.480   785  3364 W ActivityManager:   Force finishing activity com.mapswithme.maps.pro/com.mapswithme.maps.MwmActivity
06-22 11:44:58.495   785   801 I ActivityManager: Showing crash dialog for package com.mapswithme.maps.pro u0
```
Device: LG Nexus 5X (bullhead)
OS: LineageOS for MicroG
MicroG version: 0.2.7.17455
App version: 9.1.7-Google (installed from Aurora Store)

EDIT: Add a bit more logs

**Comment by CorentinCAM** [comment]
An update of microg to 0.2.8.17785-mapbox has just been released and it fixes the issue.
