### ISSUE TITLE
Android app crashes with 'couldn't find "libmapswithme.so"'

### ISSUE THREAD

**Issue by adrianalin** [mapsme/omim#11225]
I followed the steps described on https://github.com/mapsme/omim/blob/master/docs/INSTALL.md Android section, but when launching the application i get
```
    --------- beginning of crash
2019-07-15 14:49:26.362 12118-12118/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapswithme.maps.pro.beta, PID: 12118
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.mapswithme.maps.pro.beta-eV_lxr-9t8ok2CFB8ZVHjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapswithme.maps.pro.beta-eV_lxr-9t8ok2CFB8ZVHjg==/lib/arm, /data/app/com.mapswithme.maps.pro.beta-eV_lxr-9t8ok2CFB8ZVHjg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libmapswithme.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.mapswithme.maps.MwmApplication.<clinit>(MwmApplication.java:309)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1124)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1109)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:992)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5829)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
2019-07-15 14:49:26.372 2768-4184/? W/ActivityManager:   Force finishing activity com.mapswithme.maps.pro.beta/com.mapswithme.maps.DownloadResourcesActivity
```

**Comment by adrianalin** [comment]
Closing this issue because i had some local changes that was causing it.
