### ISSUE TITLE
maps_generator : No module named descriptions

### ISSUE THREAD

**Issue by a-elhaddad** [mapsme/omim#11231]
```
C:\mapswithme\omim\tools\python\maps_generator>python -m maps_generator -h
Traceback (most recent call last):
  File "C:\Users\etudiant\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\etudiant\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\mapswithme\omim\tools\python\maps_generator\maps_generator.py", line 12, in <module>
    from descriptions.descriptions_downloader import (check_and_get_checker,
ModuleNotFoundError: No module named 'descriptions'
```

**There is any step I missed?**

**Comment by tatiana-yan** [comment]
Hello.
Descriptions module is inside omim\tools\python.
Change working directory to omim\tools\python or export python path.

**Comment by a-elhaddad** [comment]
Thanks :)
