### ISSUE TITLE
Maps generator failed at routing_transit stage

### ISSUE THREAD

**Issue by Vascom** [mapsme/omim#11333]
```
ERROR env Uncaught exception: The launch of /home/vascom/mapsme0/omim-build-release/generator_tool --data_path=/home/vascom/m
apsme0/maps_build/2019_08_01__14_11_43/draft --intermediate_data_path=/home/vascom/mapsme0/maps_build/2019_08_01__14_11_43/intermediate_data --user_res
ource_path=/home/vascom/mapsme0/omim/data --transit_path=/home/vascom/mapsme0/maps_build/2019_08_01__14_11_43/intermediate_data --make_transit_cross_mw
m=true --output=Russia_Moscow Oblast_West failed.
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/__main__.py", line 243, in <module>
    main()
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/__main__.py", line 239, in main
    generate_maps(env)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/maps_generator.py", line 396, in generate_maps
    stage_mwm(env)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/decorators.py", line 35, in wrap
    func(env, *args, **kwargs)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/maps_generator.py", line 184, in stage_mwm
    chunksize=1) 
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/maps_generator.py", line 183, in <lambda>
    pool.map(lambda c: specific[c](c) if c in specific else build(c), mwms,
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/maps_generator.py", line 164, in build
    stage_routing_transit(env, country)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/decorators.py", line 84, in wrap
    func(env, country, *args, logger=_logger, **kwargs)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/decorators.py", line 65, in wrap
    func(env, country, *args, **kwargs)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/maps_generator.py", line 153, in stage_routing_transit
    stages.stage_routing_transit(env, country, **kwargs)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/stages.py", line 235, in stage_routing_transit
    **kwargs
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/stages.py", line 102, in run_gen_tool_with_recovery_country
    run_gen_tool(*args, **kwargs)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/gen_tool.py", line 145, in run_gen_tool
    GenTool(*args, **kwargs).run()
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/gen_tool.py", line 123, in run
    wait_and_raise_if_fail(self)
  File "/home/vascom/mapsme0/omim/tools/python/maps_generator/generator/exceptions.py", line 34, in wait_and_raise_if_fail
    raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /home/vascom/mapsme0/omim-build-release/generator_tool --data_path=/home/vascom/mapsme0/maps_build/2019_08_01__14_11_43/draft --intermediate_data_path=/home/vascom/mapsme0/maps_build/2019_08_01__14_11_43/intermediate_data --user_resource_path=/home/vascom/mapsme0/omim/data --transit_path=/home/vascom/mapsme0/maps_build/2019_08_01__14_11_43/intermediate_data --make_transit_cross_mwm=true --output=Russia_Moscow Oblast_West failed.
```
Workaround is --skip="routing_transit" but I am think this problem should be solved.

**Comment by tatiana-yan** [comment]
Hello!
What config do you use? Looks like you did not provide/uncomment SUBWAY_URL parameter (it's required for routing_transit).

**Comment by Vascom** [comment]
I have `SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json` string in config

**Comment by tatiana-yan** [comment]
and can you provide config to check what's wrong?

**Comment by Vascom** [comment]
```
[Main]
MAIN_OUT_PATH: ~/mapsme0/maps_build
DEBUG: 0


[Developer]
BUILD_PATH: ~/mapsme0/omim-build-release
OMIM_PATH: ~/mapsme0/omim


[Generator tool]
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# auto detection
# NODE_STORAGE: map


[Osm tools]
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
OSM_TOOLS_PATH: ~/osmctools


[Logging]
# LOG_FILE_PATH: generation.log


[External]
# PLANET_URL:
# PLANET_MD5_URL:
# PLANET_COASTS_URL:
#SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES_URL:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# SRTM_PATH:
PLANET_URL: https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf
PLANET_MD5_URL: https://download.geofabrik.de/russia/central-fed-district-latest.osm.pbf.md5
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json

[Stats]
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt

```

**Comment by tatiana-yan** [comment]
SUBWAY_URL is commented out in this file, change
```
#SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
```

to 
```
SUBWAY_URL: http://osm-subway.maps.me/mapsme/latest.json
```

**Comment by Vascom** [comment]
Hm, on latest git there is no problem.
Thanks.

**Comment by tatiana-yan** [comment]
It was a bug in transit data (http://osm-subway.maps.me/mapsme/latest.json), it was fixed recently.
