### ISSUE TITLE
unknown command line flag 'cities_boundaries_data'

### ISSUE THREAD

**Issue by jiuxs33** [mapsme/omim#12318]
1. run command   python3 -m maps_generator --countries="Thailand_*"
  Error Info:
 ```
 [2019-12-19 11:20:08,243] ERROR env Uncaught exception: The launch of /root/omim-build-release/out/release/generator_tool --data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --intermediate_data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --osm_file_type=o5m --osm_file_name=/root/maps_build/planet.o5m --node_storage=map --user_resource_path=/home/hhkx/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/root/maps_build/2019_12_19__11_18_01/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true --emit_coasts=true failed.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hhkx/omim/tools/python/maps_generator/__main__.py", line 267, in <module>
    main()
  File "/home/hhkx/omim/tools/python/maps_generator/__main__.py", line 263, in main
    generate_maps(env)
  File "/home/hhkx/omim/tools/python/maps_generator/maps_generator.py", line 396, in generate_maps
    stage_features(env)
  File "/home/hhkx/omim/tools/python/maps_generator/generator/decorators.py", line 36, in wrap
    func(env, *args, **kwargs)
  File "/home/hhkx/omim/tools/python/maps_generator/maps_generator.py", line 93, in stage_features
    stages.stage_features(env, **extra)
  File "/home/hhkx/omim/tools/python/maps_generator/generator/stages.py", line 89, in stage_features
    **kwargs
  File "/home/hhkx/omim/tools/python/maps_generator/generator/gen_tool.py", line 147, in run_gen_tool
    GenTool(*args, **kwargs).run()
  File "/home/hhkx/omim/tools/python/maps_generator/generator/gen_tool.py", line 125, in run
    wait_and_raise_if_fail(self)
  File "/home/hhkx/omim/tools/python/maps_generator/generator/exceptions.py", line 35, in wait_and_raise_if_fail
    raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /root/omim-build-release/out/release/generator_tool --data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --intermediate_data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --osm_file_type=o5m --osm_file_name=/root/maps_build/planet.o5m --node_storage=map --user_resource_path=/home/hhkx/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/root/maps_build/2019_12_19__11_18_01/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true --emit_coasts=true failed.
```
2. Then run command:
   `/root/omim-build-release/out/release/generator_tool --data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --intermediate_data_path=/root/maps_build/2019_12_19__11_18_01/intermediate_data --osm_file_type=o5m --osm_file_name=/root/maps_build/planet.o5m --node_storage=map --user_resource_path=/home/hhkx/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/root/maps_build/2019_12_19__11_18_01/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true --emit_coasts=true`

Error  Info:
```
  ERROR: unknown command line flag 'cities_boundaries_data'
  ERROR: unknown command line flag 'dump_cities_boundaries'
```

**Comment by tatiana-yan** [comment]
Hello!
Looks like tools/python/maps_generator and generator_tool have different versions.

**Comment by jiuxs33** [comment]
Hello!
But there's no problem with my Mac

**Comment by tatiana-yan** [comment]
Do you have the same sources version for both cases? Maybe you build generator_tool and then update sources and did not rebuild generator_tool? Or maybe BUILD_PATH parameter of map_generator.ini config points to some folder with old generator_tool version?
Is `generator_tool --help` the same "good" and "bad" cases and does it have `cities_boundaries_data` and `dump_cities_boundaries ` parameters?

**Comment by jiuxs33** [comment]
Thanks! 
`generator_tool` really does not have these commands. but generator_tool.cpp have these commands.
why?

**Comment by tatiana-yan** [comment]
Looks like you updated sources and did not rebuild generator_tool or build folder was configured (cmake ../omim) with bad source folder.
Can you just reconfigure and rebuild it? 
As you can see generator_tool uses gflags for options, it's simple mechanism which does not selectively hide options.

**Comment by jiuxs33** [comment]
Thank you very much!
