### ISSUE TITLE
Pushwoosh crashing

### ISSUE THREAD

**Issue by rancidfrog** [mapsme/omim#4015]
What is pushwoosh used for?
As it is part of mapswithme/util/statistics/PushwooshHelper.java
I have statistics off and offers off and no profile set and yet it is flooding logs with following error:
```
08-11 00:01:55.996 D/Pushwoosh(18456): [RequestManager] Try To send: registerUser
08-11 00:01:56.104 E/Pushwoosh(18456): [RequestManager] ERROR: failed to connect to cp.pushwoosh.com/127.0.0.1 (port 443): connect failed: ECONNREFUSED (Connection refused). Response = null
08-11 00:01:56.104 E/Pushwoosh(18456): java.net.ConnectException: failed to connect to cp.pushwoosh.com/127.0.0.1 (port 443): connect failed: ECONNREFUSED (Connection refused)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at libcore.io.IoBridge.connect(IoBridge.java:124)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at java.net.Socket.connect(Socket.java:884)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.Connection.connect(Connection.java:143)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.pushwoosh.internal.b.k.a(Unknown Source)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.pushwoosh.internal.b.k.a(Unknown Source)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.pushwoosh.PushManager.b(Unknown Source)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.pushwoosh.PushManager.a(Unknown Source)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at com.pushwoosh.PushManager$1.run(Unknown Source)
08-11 00:01:56.104 E/Pushwoosh(18456): Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at libcore.io.Posix.connect(Native Method)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
08-11 00:01:56.104 E/Pushwoosh(18456): 	at libcore.io.IoBridge.connect(IoBridge.java:122)
08-11 00:01:56.104 E/Pushwoosh(18456): 	... 22 more
```

**Comment by rancidfrog** [comment]
MAPS.ME - Offline OpenStreetMap maps
Why the need for push?
The whole idea was for offline maps, so is there a way to disable all the bloat?

**Comment by burivuh** [comment]
Hi!

We have a plan to use a setting of disabling push notifications not just to prevent receiving push messages but also to deinitializing any machinery related to pushes.

Keep updated, thank you

**Comment by rancidfrog** [comment]
Any updates on turning off push.
Also, why does it keep checking even after failure. It should check if there is errors it should stop trying to do nothing but flood logs with error!
