### ISSUE TITLE
Android - ./gradlew clean AssembleRelease build failed

### ISSUE THREAD

**Issue by Ctrl-Space** [mapsme/omim#428]
My OS is win10   
I run `./gradlew clean assembleRelease`    
but failed   
the followed info...   
- - - - - - - - - -    

++ echo 'ERROR: Can'\''t detect your host OS'
++ return 1
+ export 'NDK_HOST=ERROR: Can'\''t detect your host OS'
+ NDK_HOST='ERROR: Can'\''t detect your host OS'   

- - - - - - - - - -     

QMAKE=
+ echo 'ERROR: qmake was not found, please add it to your PATH or into the tools/autobuild/detect_qmake.sh'
ERROR: qmake was not found, please add it to your PATH or into the tools/autobuild/detect_qmake.sh

- - - - - - - - - -   

ERROR while building armeabi-v7a-hard config
+ exit 1
:cppLibsBuildRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cppLibsBuildRelease'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

 - - - - - - - - - -

**Comment by deathbaba** [comment]
What is the full build log? You can find original error message in it (just search for “Error:” string). You can share it with us via pastebin.com so we can take a look.

**Comment by Ctrl-Space** [comment]
full log   
a little bit longer   

- - - - - - - - - -   

$ ./gradlew clean assembleRelease --stacktrace

:ndkBuildClean
[armeabi-v7a-hard] Clean          : android_support [armeabi-v7a-hard]
[armeabi-v7a-hard] Clean          : c++_shared [armeabi-v7a-hard]
[armeabi-v7a-hard] Clean          : c++_static [armeabi-v7a-hard]
[armeabi-v7a-hard] Clean          : compiler_rt_shared [armeabi-v7a-hard]
[armeabi-v7a-hard] Clean          : compiler_rt_static [armeabi-v7a-hard]
[armeabi-v7a-hard] Clean          : mapswithme [armeabi-v7a-hard]
[x86] Clean          : android_support [x86]
[x86] Clean          : c++_shared [x86]
[x86] Clean          : c++_static [x86]
[x86] Clean          : compiler_rt_shared [x86]
[x86] Clean          : compiler_rt_static [x86]
[x86] Clean          : mapswithme [x86]
:clean
:3rd_party:BottomSheet:clean
:preBuild UP-TO-DATE
:preAppChinaReleaseBuild UP-TO-DATE
:checkAppChinaReleaseManifest
:preAppChinaBetaBuild UP-TO-DATE
:preAppChinaDebugBuild UP-TO-DATE
:preBaiduBetaBuild UP-TO-DATE
:preBaiduDebugBuild UP-TO-DATE
:preBaiduReleaseBuild UP-TO-DATE
:preBlackberryBetaBuild UP-TO-DATE
:preBlackberryDebugBuild UP-TO-DATE
:preBlackberryReleaseBuild UP-TO-DATE
:preCipherlabBetaBuild UP-TO-DATE
:preCipherlabDebugBuild UP-TO-DATE
:preCipherlabReleaseBuild UP-TO-DATE
:preGoogleBetaBuild UP-TO-DATE
:preGoogleDebugBuild UP-TO-DATE
:preGoogleReleaseBuild UP-TO-DATE
:preLenovoBetaBuild UP-TO-DATE
:preLenovoDebugBuild UP-TO-DATE
:preLenovoReleaseBuild UP-TO-DATE
:preMoboMarketBetaBuild UP-TO-DATE
:preMoboMarketDebugBuild UP-TO-DATE
:preMoboMarketReleaseBuild UP-TO-DATE
:preMobogenieBetaBuild UP-TO-DATE
:preMobogenieDebugBuild UP-TO-DATE
:preMobogenieReleaseBuild UP-TO-DATE
:preNineAppBetaBuild UP-TO-DATE
:preNineAppDebugBuild UP-TO-DATE
:preNineAppReleaseBuild UP-TO-DATE
:prePreinstallBetaBuild UP-TO-DATE
:prePreinstallDebugBuild UP-TO-DATE
:prePreinstallReleaseBuild UP-TO-DATE
:preSamsungBetaBuild UP-TO-DATE
:preSamsungDebugBuild UP-TO-DATE
:preSamsungReleaseBuild UP-TO-DATE
:preTencentBetaBuild UP-TO-DATE
:preTencentDebugBuild UP-TO-DATE
:preTencentReleaseBuild UP-TO-DATE
:preWebBetaBuild UP-TO-DATE
:preWebDebugBuild UP-TO-DATE
:preWebReleaseBuild UP-TO-DATE
:preXiaomiBetaBuild UP-TO-DATE
:preXiaomiDebugBuild UP-TO-DATE
:preXiaomiReleaseBuild UP-TO-DATE
:preYandexBetaBuild UP-TO-DATE
:preYandexDebugBuild UP-TO-DATE
:preYandexReleaseBuild UP-TO-DATE
:3rd_party:BottomSheet:compileLint
:3rd_party:BottomSheet:copyReleaseLint UP-TO-DATE
:3rd_party:BottomSheet:preBuild UP-TO-DATE
:3rd_party:BottomSheet:preReleaseBuild UP-TO-DATE
:3rd_party:BottomSheet:checkReleaseManifest
:3rd_party:BottomSheet:preDebugAndroidTestBuild UP-TO-DATE
:3rd_party:BottomSheet:preDebugBuild UP-TO-DATE
:3rd_party:BottomSheet:preDebugUnitTestBuild UP-TO-DATE
:3rd_party:BottomSheet:preReleaseUnitTestBuild UP-TO-DATE
:3rd_party:BottomSheet:prepareComAndroidSupportSupportV42220Library
:3rd_party:BottomSheet:prepareReleaseDependencies
:3rd_party:BottomSheet:compileReleaseAidl
:3rd_party:BottomSheet:compileReleaseRenderscript
:3rd_party:BottomSheet:generateReleaseBuildConfig
:3rd_party:BottomSheet:generateReleaseAssets UP-TO-DATE
:3rd_party:BottomSheet:mergeReleaseAssets
:3rd_party:BottomSheet:generateReleaseResValues UP-TO-DATE
:3rd_party:BottomSheet:generateReleaseResources
:3rd_party:BottomSheet:mergeReleaseResources
:3rd_party:BottomSheet:processReleaseManifest
:3rd_party:BottomSheet:processReleaseResources
:3rd_party:BottomSheet:generateReleaseSources
:3rd_party:BottomSheet:processReleaseJavaRes UP-TO-DATE
:3rd_party:BottomSheet:compileReleaseJavaWithJavacע: D:\AndroidProjects\omim\android\3rd_party\BottomSheet\src\main\java\com\cocosw\bottomsheet\BottomSheet.javaʹ▒û򸲸▒▒▒▒ѹ▒ʱ▒▒ API▒▒
ע: ▒й▒▒▒ϸ▒▒Ϣ, ▒▒ʹ▒▒ -Xlint:deprecation ▒▒▒±▒▒롣

:3rd_party:BottomSheet:extractReleaseAnnotations
:3rd_party:BottomSheet:mergeReleaseProguardFiles UP-TO-DATE
:3rd_party:BottomSheet:packageReleaseJar
:3rd_party:BottomSheet:compileReleaseNdk UP-TO-DATE
:3rd_party:BottomSheet:packageReleaseJniLibs UP-TO-DATE
:3rd_party:BottomSheet:packageReleaseLocalJar UP-TO-DATE
:3rd_party:BottomSheet:packageReleaseRenderscript UP-TO-DATE
:3rd_party:BottomSheet:packageReleaseResources
:3rd_party:BottomSheet:bundleRelease
:prepareAndroid3rd_partyBottomSheetUnspecifiedLibrary
:prepareComAndroidSupportAppcompatV72221Library
:prepareComAndroidSupportDesign2221Library
:prepareComAndroidSupportRecyclerviewV72221Library
:prepareComAndroidSupportSupportV42221Library
:prepareComFacebookAndroidFacebookAndroidSdk460Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics780Library
:prepareComGoogleAndroidGmsPlayServicesBase780Library
:prepareComGoogleAndroidGmsPlayServicesLocation780Library
:prepareComGoogleAndroidGmsPlayServicesMaps780Library
:prepareComGoogleAndroidGmsPlayServicesPlus780Library
:prepareOrgSolovyevAndroidViewsLinearLayoutManager05Library
:prepareAppChinaReleaseDependencies
:compileAppChinaReleaseAidl
:compileAppChinaReleaseRenderscript
:generateAppChinaReleaseBuildConfig
:generateAppChinaReleaseAssets UP-TO-DATE
:mergeAppChinaReleaseAssets
:generateAppChinaReleaseResValues UP-TO-DATE
:generateAppChinaReleaseResources
:mergeAppChinaReleaseResources
:processAppChinaArmeabi-v7aReleaseManifest
:processAppChinaArmeabi-v7aReleaseResources
:processAppChinaUniversalReleaseManifest
:processAppChinaUniversalReleaseResources
:processAppChinaX86ReleaseManifest
:processAppChinaX86ReleaseResources
:generateAppChinaReleaseSources
:cppLibsBuildReleasebash.exe: warning: could not find /tmp, please create!
++ dirname ../tools/autobuild/android.sh
+ MY_PATH=../tools/autobuild
++ cd ../tools/autobuild
++ pwd
+ MY_PATH=D:/AndroidProjects/omim/tools/autobuild
+ [[ 1 < 1 ]]
+ CONFIGURATION=production
+ source D:/AndroidProjects/omim/tools/autobuild/build.sh
++ set -e -x -u
+++ dirname ../tools/autobuild/android.sh
++ MY_PATH=../tools/autobuild
+++ cd ../tools/autobuild
+++ pwd
++ MY_PATH=D:/AndroidProjects/omim/tools/autobuild
++ source D:/AndroidProjects/omim/tools/autobuild/detect_qmake.sh
+++ KNOWN_QMAKE_PATHS=(/Developer/Tools/qmake ~/Developer/Qt-4.8.4/bin/qmake ~/Developer/Qt/5.1.0/clang_64/bin/qmake ~/Developer/Qt/5.1.1/clang_64/bin/qmake ~/Developer/Qt/5.2.0/clang_64/bin/qmake ~/Developer/Qt/5.2.1/clang_64/bin/qmake ~/Qt/5.2.1/clang_64/bin/qmake ~/Developer/Qt/5.3/clang_64/bin/qmake ~/Qt/5.3/clang_64/bin/qmake ~/Qt/5.4/clang_64/bin/qmake ~/Qt/5.5/clang_64/bin/qmake ~/Qt5.3.0/5.3/clang_64/bin/qmake ~/Developer/Qt/5.4/clang_64/bin/qmake ~/Developer/Qt/5.5/clang_64/bin/qmake /usr/local/opt/qt5/bin/qmake /cygdrive/c/Qt/5.5/msvc2013_64/bin/qmake.exe)
+ source D:/AndroidProjects/omim/tools/autobuild/ndk_helper.sh
++ set -e -u
+++ dirname ../tools/autobuild/android.sh
++ MY_PATH=../tools/autobuild
+++ cd ../tools/autobuild
+++ pwd
++ MY_PATH=D:/AndroidProjects/omim/tools/autobuild
+ MKSPEC=D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang
+ QMAKE_PARAMS=CONFIG+=production
+ SHADOW_DIR_BASE=D:/AndroidProjects/omim/tools/autobuild/../../../omim-android
++ GetNdkRoot
++ local FILENAME=D:/AndroidProjects/omim/tools/autobuild/../../android/local.properties
++ read line
++ [[ # Autog == \n\d\k\.\d\i\r ]]
++ read line
++ [[ # Do no == \n\d\k\.\d\i\r ]]
++ read line
++ [[ sdk.dir == \n\d\k\.\d\i\r ]]
++ read line
++ [[ ndk.dir == \n\d\k\.\d\i\r ]]
'+ echo 'D:\AndroidNDK\android-ndk
++ return 0
+ export 'NDK_ROOT=D:\AndroidNDK\android-ndk'
+ NDK_ROOT='D:\AndroidNDK\android-ndk'
++ GetNdkHost
++ [[ msys == \l\i\n\u\x ]]
++ [[ msys == \d\a\r\w\i\n ]]
++ [[ msys == \c\y\g\w\i\n ]]
++ echo 'ERROR: Can'\''t detect your host OS'
++ return 1
+ export 'NDK_HOST=ERROR: Can'\''t detect your host OS'
+ NDK_HOST='ERROR: Can'\''t detect your host OS'
+ [[ 1 > 2 ]]
+ [[ 1 > 1 ]]
+ NDK_ABI_LIST=(armeabi-v7a-hard x86)
+ for abi in '"${NDK_ABI_LIST[@]}"'
+ SHADOW_DIR=D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard
+ export NDK_ABI=armeabi-v7a-hard
+ NDK_ABI=armeabi-v7a-hard
+ BuildQt D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang CONFIG+=production
++ PrintQmakePath
++ local QMAKE_PATH
+++ which qmake
which: no qmake in (/c/Users/文杰/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/mingw64/bin:/usr/bin:/c/Python27:/c/Python27/Scripts:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/ATI Technologies/ATI.ACE/Core-Static:/c/ProgramData/Lenovo/ReadyApps:/c/Program Files/TortoiseSVN/bin:/c/Program Files/Java/jdk1.8.0_45/bin:/c/Program Files/Java/jre1.8.0_45/bin:/c/Users/文杰/AppData/Local/atom/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
++ QMAKE_PATH=
++ '[' 1 -ne 0 ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f /Developer/Tools/qmake ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt-4.8.4/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.1.0/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.1.1/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.2.0/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.2.1/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Qt/5.2.1/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.3/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Qt/5.3/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Qt/5.4/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Qt/5.5/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Qt5.3.0/5.3/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.4/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f $'/c/Users/▒\226\207▒\235?/Developer/Qt/5.5/clang_64/bin/qmake' ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f /usr/local/opt/qt5/bin/qmake ']'
++ for path in '"${KNOWN_QMAKE_PATHS[@]}"'
++ '[' -f /cygdrive/c/Qt/5.5/msvc2013_64/bin/qmake.exe ']'
++ return 1
+ QMAKE=
+ echo 'ERROR: qmake was not found, please add it to your PATH or into the tools/autobuild/detect_qmake.sh'
ERROR: qmake was not found, please add it to your PATH or into the tools/autobuild/detect_qmake.sh
+ exit 1
+ SHADOW_DIR=D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard
+ MKSPEC=D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang
+ QMAKE_PARAMS=CONFIG+=production
+ mkdir -p D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard
+ cd D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard
+ '[' '!' -f D:/AndroidProjects/omim/tools/autobuild/../../../omim-android-production-armeabi-v7a-hard/Makefile ']'
+ echo 'Launching qmake...'
Launching qmake...
++ StripCygwinPrefix D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang
+++ GetNdkHost
+++ [[ msys == \l\i\n\u\x ]]
+++ [[ msys == \d\a\r\w\i\n ]]
+++ [[ msys == \c\y\g\w\i\n ]]
+++ echo 'ERROR: Can'\''t detect your host OS'
+++ return 1
++ [[ ERROR: Can't detect your host OS == \w\i\n\d\o\w\s\-\x\8\6\_\6\4 ]]
++ echo D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang
++ return 0
++ StripCygwinPrefix D:/AndroidProjects/omim/tools/autobuild
+++ GetNdkHost
+++ [[ msys == \l\i\n\u\x ]]
+++ [[ msys == \d\a\r\w\i\n ]]
+++ [[ msys == \c\y\g\w\i\n ]]
+++ echo 'ERROR: Can'\''t detect your host OS'
+++ return 1
++ [[ ERROR: Can't detect your host OS == \w\i\n\d\o\w\s\-\x\8\6\_\6\4 ]]
++ echo D:/AndroidProjects/omim/tools/autobuild
++ return 0
+ '' CONFIG-=sdk -r CONFIG+=production -spec D:/AndroidProjects/omim/tools/autobuild/../mkspecs/android-clang D:/AndroidProjects/omim/tools/autobuild/../../omim.pro
D:/AndroidProjects/omim/tools/autobuild/build.sh: line 55: : command not found
++ GetCPUCores
++ case "$OSTYPE" in
++ echo 'Unsupported platform in ../tools/autobuild/android.sh'
++ exit 1
+ make -j Unsupported platform in ../tools/autobuild/android.sh
D:/AndroidProjects/omim/tools/autobuild/build.sh: line 58: make: command not found
+ echo 'ERROR while building armeabi-v7a-hard config'
+ exit 1

ERROR while building armeabi-v7a-hard config
:cppLibsBuildRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cppLibsBuildRelease'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cppLibsBuildRelease'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:155)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:152)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:100)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:94)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:94)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'bash'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:367)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
        at org.gradle.api.tasks.AbstractExecTask.exec(AbstractExecTask.java:54)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more


BUILD FAILED

Total time: 1 mins 4.522 secs
- - - - - - - - - -    
Thank you for your attention!

**Comment by Ctrl-Space** [comment]
I wasn`t had install QT   
Is the reason for this problem?

**Comment by deathbaba** [comment]
Yes, of course. qmake is required to build C++ core part. And here is an error from your log:

ERROR: qmake was not found, please add it to your PATH or into the tools/autobuild/detect_qmake.sh

**Comment by xingdavis** [comment]
I've had the same problem.however, I have installed QT
![1](https://cloud.githubusercontent.com/assets/11851006/11061240/9ad0e5f0-87e0-11e5-9d29-144b238c611b.png)

**Comment by trashkalmar** [comment]
@xingdavis You should use NDK r10e.

**Comment by xingdavis** [comment]
@trashkalmar After point to the r10e, how to clear the old file

**Comment by xingdavis** [comment]
@trashkalmar  Re run set_up_android.py --ndk /home/soft/android_dev_evn/android-ndk-r10e,
./gradlew clean assembleWebRelease
Still like this 
 
![1](https://cloud.githubusercontent.com/assets/11851006/11062111/31fd0f7a-87e7-11e5-8d46-f7ec655fee04.png)

**Comment by trashkalmar** [comment]
@xingdavis Please ensure, that the ndk inside local.properties points to r10e folder.
Actually, cleanup via gradle does not clean everything. Go to project's root parent directory and delete omim-* folders.

**Comment by deathbaba** [comment]
clang is not found - you don't have compiler installed in your path.

**Comment by deathbaba** [comment]
Still r9e ndk. Please check local.properties file in android folder

**Comment by xingdavis** [comment]
@trashkalmar @deathbaba compiler ,Do you mean installing QT？
The ‘local.properties’ file has been updated, but it's still a hint of the old one.
![image](https://cloud.githubusercontent.com/assets/11851006/11081465/cb141b98-8857-11e5-9802-b5ae770acc9f.png)

**Comment by deathbaba** [comment]
@trashkalmar Can you try to set up build environment from scratch on a test Windows machine and update our documentation about toolchain? For sure we’ll have more and more questions about “how to do it on Windows”. Btw, few years ago I was able to compile everything with mingw built-in into msysgit distribution, without any cygwin.

**Comment by trashkalmar** [comment]
@deathbaba Sure, we must update documentation for building under Windows once. I'll create a trello card.

**Comment by xingdavis** [comment]
@deathbaba @trashkalmar Okay, I'll try it.Thanks!
Follow this guide?
https://github.com/mapsme/omim/blob/master/docs/android_toolchain_windows.txt

**Comment by trashkalmar** [comment]
@xingdavis this guide is very old and obsolete. It will not help you.

**Comment by xingdavis** [comment]
@trashkalmar build android project,what os environment compiler is appropriate?

**Comment by trashkalmar** [comment]
@xingdavis Ideally you should compile under MacOS. For Windows the compilation is set up for x64 OS and Cygwin environment.

**Comment by deathbaba** [comment]
@xingdavis if it's ok, can you please close the issue?
P.S. Would be great if you share all "windows-related" knowledge in documentation.

**Comment by xingdavis** [comment]
@deathbabaThank you for your help, the problem has been solved.but  I don't have permission to close this issue.

**Comment by deathbaba** [comment]
Ooops, @Ctrl-Space what about you?

**Comment by Georgiy** [comment]
I have get the following error 
Error:Execution failed for task ':cppBuildRelease'.
> Process 'command 'bash'' finished with non-zero exit value 1

And solve it by changing in the gradle 
 armeabi-v7a-hard to just  armeabi-v7a

Since the  armeabi-v7a-hard depricated

**Comment by deathbaba** [comment]
There are two places to change armeabi-v7a-hard to armeabi-v7a for new NDKs:
- https://github.com/mapsme/omim/blob/master/tools/autobuild/android.sh
- https://github.com/mapsme/omim/blob/master/android/jni/Application.mk
