### ISSUE TITLE
Crash when i compile master since merge release-64

### ISSUE THREAD

**Issue by fijemax** [mapsme/omim#4386]
I have this crash when i lunch the master since merge with release-64 : 

```
09-26 17:19:43.090 863-874/? I/ActivityManager: Killing 31283:com.mapswithme.maps.pro/u0a150 (adj 900): crash
09-26 17:19:43.093 863-874/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mapswithme.maps.pro/com.mapswithme.maps.DownloadResourcesActivity bnds=[84,284][252,452] (has extras)} from uid 10031 on display 0
09-26 17:19:43.147 863-3357/? I/ActivityManager: Start proc 31328:com.mapswithme.maps.pro/u0a150 for activity com.mapswithme.maps.pro/com.mapswithme.maps.DownloadResourcesActivity
                                                 
                                                 --------- beginning of main
09-26 17:19:43.238 31328-31328/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.mapswithme.maps.pro, PID: 31328
                                                   java.lang.RuntimeException: Unable to create application com.mapswithme.maps.MwmApplication: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
                                                       at io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
                                                       at io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
                                                       at com.crashlytics.android.Crashlytics.getInstance(Crashlytics.java:188)
                                                       at com.crashlytics.android.Crashlytics.checkInitialized(Crashlytics.java:371)
                                                       at com.crashlytics.android.Crashlytics.setString(Crashlytics.java:266)
                                                       at com.mapswithme.maps.MwmApplication.setInstallationIdToCrashlytics(MwmApplication.java:208)
                                                       at com.mapswithme.maps.MwmApplication.onCreate(MwmApplication.java:114)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
09-26 17:19:43.241 863-3357/? W/ActivityManager:   Force finishing activity com.mapswithme.maps.pro/com.mapswithme.maps.DownloadResourcesActivity
09-26 17:19:43.316 863-883/? I/WindowManager: Destroying surface Surface(name=Application Error: com.mapswithme.maps.pro) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:429 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:232 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:180 com.android.server.wm.WindowManagerService$H.handleMessage:8079 android.os.Handler.dispatchMessage:102 
09-26 17:19:43.747 863-876/? W/ActivityManager: Activity pause timeout for ActivityRecord{490b5a1 u0 com.mapswithme.maps.pro/com.mapswithme.maps.DownloadResourcesActivity t187 f}
09-26 17:19:44.281 863-883/? I/WindowManager: Destroying surface Surface(name=Starting com.mapswithme.maps.pro) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.AppWindowToken.destroySurfaces:365 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:176 
```

**Comment by alexzatsepin** [comment]
Hey @fijemax ! Could you check please your fabric.properties file located in the root of android directory. Is the 'apiKey' value looked like '000000...' or not?

**Comment by fijemax** [comment]
yes the api key is : 
apiKey=0000000000000000000000000000000000000000

**Comment by alexzatsepin** [comment]
Thanks for letting me know. I fixed this problem here https://github.com/mapsme/omim/pull/4387 . While t will be on code review you can just copy my changes into your fork and continue to work with the master branch.

**Comment by fijemax** [comment]
Thank you for the fast answer. I close issue.
