### ISSUE TITLE
Force close when Android device rotates

### ISSUE THREAD

**Issue by abforce** [mapsme/omim#6752]
When I rotate my device from portrait to landscape, maps.me stops working and is force closed. Here the logcat:

```
07-31 12:00:20.185 15309 15309 E AndroidRuntime: FATAL EXCEPTION: main
07-31 12:00:20.185 15309 15309 E AndroidRuntime: Process: com.mapswithme.maps.pro, PID: 15309
07-31 12:00:20.185 15309 15309 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapswithme.maps.pro/com.mapswithme.maps.MwmActivity}: android.view.InflateException: Binary XML file line #72: Binary XML file line #72: Error inflating class <unknown>
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #72: Binary XML file line #72: Error inflating class <unknown>
07-31 12:00:20.185 15309 15309 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #72: Error inflating class <unknown>
07-31 12:00:20.185 15309 15309 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.MwmActivity.safeOnCreate(MwmActivity.java:499)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.base.BaseMwmFragmentActivity.onCreate(BaseMwmFragmentActivity.java:68)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6679)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4519)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.ugc.UgcAverageRatingController.<init>(UgcAverageRatingController.java:17)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.widget.placepage.PlacePageView.initUgcView(PlacePageView.java:657)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.widget.placepage.PlacePageView.initViews(PlacePageView.java:451)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.widget.placepage.PlacePageView.init(PlacePageView.java:1003)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.widget.placepage.PlacePageView.<init>(PlacePageView.java:325)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	at com.mapswithme.maps.widget.placepage.PlacePageView.<init>(PlacePageView.java:315)
07-31 12:00:20.185 15309 15309 E AndroidRuntime: 	... 28 more
```

I built its Android client myself using the following commands:

```
$ git clone https://github.com/mapsme/omim.git
$ cd omim
$ ./configure.sh
$ tools/android/set_up_android.py
$ cd android
$ ./gradlew runWebRelease
```

App runs successfully, but downloading maps doesn't work and when device rotates it stops. More info follow:
 - Android 7.1.1 on Nexus 5X
 - Maps.me 7.4.4-web

Note that because my build couldn't download maps, I downloaded them using official build from Google Play and then removed that `google` version and installed my build.

**Comment by alexzatsepin** [comment]
@abforce This crash should be already fixed in the master. Please check and let me know if you have any questions.
