### ISSUE TITLE
Couldn't find "libmapswithme.so" when use fresco.

### ISSUE THREAD

**Issue by huynhvan257** [mapsme/omim#6928]
I'm facing with a big problem, Please help me.
I want use fresco for mapsme project, but error when load libmapswithme.so  (device Sony) . Samsung can run
Thank all.

http://frescolib.org/docs/shipping.html

> java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "xxx/base.apk"],nativeLibraryDirectories=/lib/arm64, /base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libmapswithme.so"
>                                                        at java.lang.Runtime.loadLibrary(Runtime.java:367)
>                                                        at java.lang.System.loadLibrary(System.java:1076)
>                                                        at com.mapswithme.maps.MwmApplication.<clinit>(MwmApplication.java:256)
>                                                        at java.lang.Class.newInstance(Native Method)
>                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:997)
>                                                        at android.app.Instrumentation.newApplication(Instrumentation.java:982)
>                                                        at android.app.LoadedApk.makeApplication(LoadedApk.java:577)
>                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4777)
>                                                        at android.app.ActivityThread.access$1600(ActivityThread.java:154)
>                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1450)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                        at android.os.Looper.loop(Looper.java:224)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5514)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by huynhvan257** [comment]
I found solution.

add to gradle.

  packagingOptions {
    ....

    exclude "lib/armeabi/libbitmaps.so"
    exclude "lib/armeabi/libgifimage.so"
    exclude "lib/armeabi/libimagepipeline.so"
    exclude "lib/armeabi/libmemchunk.so"
    exclude "lib/armeabi/libwebp.so"
    exclude "lib/armeabi/libwebpimage.so"
    exclude "lib/arm64-v8a/libbitmaps.so"
    exclude "lib/arm64-v8a/libgifimage.so"
    exclude "lib/arm64-v8a/libimagepipeline.so"
    exclude "lib/arm64-v8a/libmemchunk.so"
    exclude "lib/arm64-v8a/libwebp.so"
    exclude "lib/arm64-v8a/libwebpimage.so"
    exclude "lib/x86_64/libbitmaps.so"
    exclude "lib/x86_64/libgifimage.so"
    exclude "lib/x86_64/libimagepipeline.so"
    exclude "lib/x86_64/libmemchunk.so"
    exclude "lib/x86_64/libwebp.so"
    exclude "lib/x86_64/libwebpimage.so"
  }
