### ISSUE TITLE
error while running webdebug android 

### ISSUE THREAD

**Issue by mohanedmoh** [mapsme/omim#9517]
E/Pushwoosh: [RequestManager] ERROR: Unable to resolve host "xxxxx.api.pushwoosh.com": No address associated with hostname
    com.pushwoosh.internal.network.b: Unable to resolve host "xxxxx.api.pushwoosh.com": No address associated with hostname
        at com.pushwoosh.internal.network.d.a(Unknown Source:178)
        at com.pushwoosh.internal.network.d.a(Unknown Source:0)
        at com.pushwoosh.internal.network.e.run(Unknown Source:8)
        at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source:47)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
09-24 12:56:13.743 26804-26804/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26804 (e.maps.pro.beta)
09-24 12:56:13.776 26870-26870/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint:

**Comment by mohanedmoh** [comment]
any help here ??????????????????

**Comment by alexzatsepin** [comment]
Hi @mohanedmoh ,

Could you provide the whole crash dump beginning with the string "Fatal signal 6..."?

**Comment by mohanedmoh** [comment]
0-08 12:09:20.237 22405-22405/com.mapswithme.maps.pro.debug A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 22405 (.maps.pro.debug)
10-08 12:09:20.321 22623-22623/? I/crash_dump32: obtaining output fd from tombstoned
10-08 12:09:20.322 1304-1304/? I//system/bin/tombstoned: received crash request for pid 22405
10-08 12:09:20.323 22623-22623/? I/crash_dump32: performing dump of process 22405 (target tid = 22405)
10-08 12:09:20.324 22623-22623/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'htc/ocmdugl_00401/htc_ocmdugl:8.0.0/OPR6.170623.013/1010171.7:user/release-keys'
    Revision: '0'
    ABI: 'arm'
    pid: 22405, tid: 22405, name: .maps.pro.debug  >>> com.mapswithme.maps.pro.debug <<<
    signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
10-08 12:09:20.326 22623-22623/? A/DEBUG: Abort message: 'java_vm_ext.cc:542] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0x98'
        r0 00000000  r1 00005785  r2 00000006  r3 00000008
        r4 00005785  r5 00005785  r6 fff13ff0  r7 0000010c
        r8 00000015  r9 fff14051  sl 0000000a  fp fff14050
        ip 00000000  sp fff13fe0  lr e9e359e7  pc e9e6726c  cpsr 200e0010
10-08 12:09:20.341 22623-22623/? A/DEBUG: backtrace:
        #00 pc 0004c26c  /system/lib/libc.so (tgkill+12)
        #01 pc 0001a9e3  /system/lib/libc.so (abort+54)
        #02 pc 0033c657  /system/lib/libart.so (_ZN3art7Runtime5AbortEPKc+230)
        #03 pc 0033cce7  /system/lib/libart.so (_ZN3art7Runtime7AborterEPKc+10)
        #04 pc 003f473d  /system/lib/libart.so (_ZN7android4base10LogMessageD1Ev+456)
        #05 pc 002336e7  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1262)
        #06 pc 002338cf  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortVEPKcS2_St9__va_list+58)
        #07 pc 000d2a8f  /system/lib/libart.so (_ZN3art11ScopedCheck6AbortFEPKcz+46)
        #08 pc 000d2e21  /system/lib/libart.so (_ZN3art11ScopedCheck14CheckUtfStringEPKcb+504)
        #09 pc 000d0e27  /system/lib/libart.so (_ZN3art11ScopedCheck5CheckERNS_18ScopedObjectAccessEbPKcPNS_12JniValueTypeE+606)
        #10 pc 000c93b1  /system/lib/libart.so (_ZN3art8CheckJNI12NewStringUTFEP7_JNIEnvPKc+452)
        #11 pc 00f2c603  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7_JNIEnv12NewStringUTFEPKc+38)
        #12 pc 00f2c5d5  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN3jni12ToJavaStringEP7_JNIEnvPKc+22)
        #13 pc 00f2e091  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN3jni12ToJavaStringEP7_JNIEnvRKNSt6__ndk112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE+132)
        #14 pc 00f2ff7b  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN3jni14AndroidMessageEN4base8LogLevelERKNS0_8SrcPointERKNSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE+638)
10-08 12:09:20.342 22623-22623/? A/DEBUG:     #15 pc 00f30a5d  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN3jni20AndroidAssertMessageERKN4base8SrcPointERKNSt6__ndk112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEE+36)
        #16 pc 019b1c09  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZNK13Classificator13GetTypeByPathERKSt16initializer_listIPKcE+160)
        #17 pc 01394b9d  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing12VehicleModel18AdditionalRoadTypeC1ERK13ClassificatorRKNS0_18AdditionalRoadTagsE+40)
        #18 pc 0139a189  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZNSt6__ndk16vectorIN7routing12VehicleModel18AdditionalRoadTypeENS_9allocatorIS3_EEE24__emplace_back_slow_pathIJRK13ClassificatorRKNS2_18AdditionalRoadTagsEEEEvDpOT_+368)
        #19 pc 01396a01  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing12VehicleModel22SetAdditionalRoadTypesERK13ClassificatorRKNSt6__ndk16vectorINS0_18AdditionalRoadTagsENS4_9allocatorIS6_EEEE+412)
        #20 pc 0138e23d  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing8CarModel23InitAdditionalRoadTypesEv+32)
        #21 pc 0138e283  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing8CarModelC1ERKSt16initializer_listINS_12VehicleModel17FeatureTypeLimitsEE+58)
        #22 pc 013912ad  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZNSt6__ndk110shared_ptrIN7routing8CarModelEE11make_sharedIJRKSt16initializer_listINS1_12VehicleModel17FeatureTypeLimitsEEEEES3_DpOT_+556)
        #23 pc 0138e3d1  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing15CarModelFactoryC1ERKNSt6__ndk18functionIFNS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEERKS8_EEE+72)
        #24 pc 01277853  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZNSt6__ndk110shared_ptrIN7routing15CarModelFactoryEE11make_sharedIJRKNS_8functionIFNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERKSB_EEEEEES3_DpOT_+546)
        #25 pc 01267f85  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so
        #26 pc 0126735f  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7routing11IndexRouterC1ENS_11VehicleTypeEbRKNSt6__ndk18functionIFNS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEERKS9_EEERKNS3_IFS9_RKN2m25PointIdEEEEERKNS3_IFNSG_4RectIdEESB_EEENS2_10shared_ptrINS_9NumMwmIdsEEENS2_10unique_ptrIN2m44TreeItNSZ_9TraitsDefItEEEENS2_14default_deleteIS13_EEEERKN7traffic12TrafficCacheER10DataSource+306)
        #27 pc 011789ab  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN14RoutingManager13SetRouterImplEN7routing10RouterTypeE+1262)
        #28 pc 010b03cb  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN9FrameworkC1ERK15FrameworkParams+13854)
        #29 pc 00f70d09  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (_ZN7android9FrameworkC1Ev+128)
        #30 pc 00f9c5a3  /data/app/com.mapswithme.maps.pro.debug-RCk0iJOFNBmWaFGEX98q_g==/lib/arm/libmapswithme.so (Java_com_mapswithme_maps_MwmApplication_nativeInitFramework+74)
        #31 pc 003e58a9  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
        #32 pc 003e1b61  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
        #33 pc 003e61db  /system/lib/libart.so (art_quick_invoke_static_stub+226)
        #34 pc 000ac8d3  /system/lib/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+182)
        #35 pc 001f53b7  /system/lib/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+238)
        #36 pc 001f0967  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+574)
        #37 pc 003ccb0d  /system/lib/libart.so (MterpInvokeStatic+324)
        #38 pc 003d3f94  /system/lib/libart.so (ExecuteMterpImpl+14612)
        #39 pc 001d7ee9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
        #40 pc 001dd26b  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
        #41 pc 001f0951  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
        #42 pc 003cc911  /system/lib/libart.so (MterpInvokeDirect+360)
        #43 pc 003d3f14  /system/lib/libart.so (ExecuteMterpImpl+14484)
        #44 pc 001d7ee9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
        #45 pc 001dd26b  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
        #46 pc 001f0951  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
        #47 pc 003cba5b  /system/lib/libart.so (MterpInvokeVirtual+446)
        #48 pc 003d3e14  /system/lib/libart.so (ExecuteMterpImpl+14228)
        #49 pc 001d7ee9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
        #50 pc 001dd26b  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
        #51 pc 001f0951  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
        #52 pc 003cc911  /system/lib/libart.so (MterpInvokeDirect+360)
        #53 pc 003d3f14  /system/lib/libart.so (ExecuteMterpImpl+14484)
        #54 pc 001d7ee9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
        #55 pc 001dd26b  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
        #56 pc 001f0951  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
        #57 pc 003ccb0d  /system/lib/libart.so (MterpInvokeStatic+324)
        #58 pc 003d3f94  /system/lib/libart.so (ExecuteMterpImpl+14612)
        #59 pc 001d7ee9  /system/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadEPKNS_7DexFile8CodeItemERNS_11ShadowFrameENS_6JValueEb+340)
        #60 pc 001dd26b  /system/lib/libart.so (_ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadEPKNS_7DexFile8CodeItemEPNS_11ShadowFrameEPNS_6JValueE+142)
        #61 pc 001f0951  /system/lib/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+552)
        #62 pc 003cc687  /system/lib/libart.so (MterpInvokeInterface+1198)
        #63 pc 003d4014  /system/lib/libart.so (ExecuteMterpImpl+14740)
10-08 12:09:20.711 2020-2020/? D/NetworkController: [DataActivity][1][GSM] NONE
10-08 12:09:20.715 2020-2020/? D/NetworkController: DataModel State = 0 hasDataRegService = false DataConnected :false hasVoiceRegService: true PhoneType : 1 DataNetType :0 slot =0
10-08 12:09:20.719 2020-2020/? D/NetworkController: roaming : false
10-08 12:09:20.720 2020-2020/? E/NetworkController: GSM STATE_IN_SERVICE mESimEnable = false, slot 0
10-08 12:09:20.720 2020-2020/? D/NetworkController: level=5/5
    isDualSimDualStandby : SignaltheOtherDM.mPhoneState : 0
10-08 12:09:20.725 2020-2020/? D/NetworkController: DataModel State = 0 hasDataRegService = true DataConnected :true hasVoiceRegService: true PhoneType : 1 DataNetType :15 slot =1
10-08 12:09:20.728 2020-2020/? D/NetworkController: RilDataRadioTechnology : 15 mPhoneState :  0
10-08 12:09:20.729 2020-2020/? D/NetworkController: roaming : false
10-08 12:09:20.729 2020-2020/? E/NetworkController: GSM STATE_IN_SERVICE mESimEnable = false, slot 1
10-08 12:09:20.729 2020-2020/? D/NetworkController: level=2/5
    isDualSimDualStandby : SignaltheOtherDM.mPhoneState : 0
10-08 12:09:20.730 2020-2020/? D/SignalClusterView: vpn: GONE
10-08 12:09:20.731 2020-2020/? D/SignalClusterView: wifi=G,stat_sys_wifi_signal_connected_0 air=G,stat_sys_signal_flightmode data[0]=G,(null) sig[0]=V,cdma_stat_sys_s1_5signal_5 data[1]=V,stat_sys_data_connected_h sig[1]=V,cdma_stat_sys_s2_5signal_2
    vpn: GONE
    wifi=G,stat_sys_wifi_signal_connected_0 air=G,stat_sys_signal_flightmode data[0]=G,(null) sig[0]=V,cdma_stat_sys_s1_5signal_5 data[1]=V,stat_sys_data_connected_h sig[1]=V,cdma_stat_sys_s2_5signal_2
10-08 12:09:21.539 1304-1304/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_06
10-08 12:09:21.541 1757-22624/? E/ActivityManager: App crashed! Process: com.mapswithme.maps.pro.debug

**Comment by amenk** [comment]
I seem to get a similar crash ...

       10-14 14:37:56.716 18587 18587 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI NewStringUTF called with pending exception java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapswithme.util.statistics.PushwooshHelper.sendTags(java.lang.String, java.lang.String[])' on a null object reference'

**Comment by innodeltech** [comment]
Where is pushwoosh.properties file?
