### ISSUE TITLE
error while running android project o debug mode

### ISSUE THREAD

**Issue by mohanedmoh** [mapsme/omim#9561]
at com.mapswithme.maps.MwmApplication.nativeInitFramework(Native method)
    runtime.cc:492]   at com.mapswithme.maps.MwmApplication.initNativeFramework(MwmApplication.java:272)
    runtime.cc:492]   at com.mapswithme.maps.MwmApplication.initCore(MwmApplication.java:212)
    runtime.cc:492]   at com.mapswithme.maps.SplashActivity.init(SplashActivity.java:331)
    runtime.cc:492]   at com.mapswithme.maps.SplashActivity.access$000(SplashActivity.java:34)
    runtime.cc:492]   at com.mapswithme.maps.SplashActivity$2.run(SplashActivity.java:70)
    runtime.cc:492]   at android.os.Handler.handleCallback(Handler.java:789)
    runtime.cc:492]   at android.os.Handler.dispatchMessage(Handler.java:98)
    runtime.cc:492]   at android.os.Looper.loop(Looper.java:180)
    runtime.cc:492]   at android.app.ActivityThread.main(ActivityThread.java:6950)
    runtime.cc:492]   at java.lang.reflect.Method.invoke(Native method)
    runtime.cc:492]   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    runtime.cc:492]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:835)
    runtime.cc:492]

**Comment by alexzatsepin** [comment]
Hi @mohanedmoh,

Please recheck it. Fixed here https://github.com/mapsme/omim/pull/9797.
