### ISSUE TITLE
Crash when selecting POI: NullPointerException: Attempt to invoke interface method 'boolean com.mapswithme.maps.purchase.PurchaseController.isPurchaseSupported()'

### ISSUE THREAD

**Issue by amenk** [mapsme/omim#9708]
0 09:44:29.393 12627 12627 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.mapswithme.maps.purchase.PurchaseController.isPurchaseSupported()' on a null object reference
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.widget.placepage.BannerController.updateVisibility(BannerController.java:223)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.widget.placepage.BannerController.access$1000(BannerController.java:47)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.widget.placepage.BannerController$MyNativeAdsListener.onAdLoaded(BannerController.java:441)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.ads.CompoundNativeAdLoader.onAdLoadingCompleted(CompoundNativeAdLoader.java:204)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.ads.CompoundNativeAdLoader.onAdLoaded(CompoundNativeAdLoader.java:145)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.ads.CachingNativeAdLoader.onAdLoaded(CachingNativeAdLoader.java:133)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mapswithme.maps.ads.MopubNativeDownloader.onNativeLoad(MopubNativeDownloader.java:97)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mopub.nativeads.MoPubNative$3.onNativeAdLoaded(MoPubNative.java:212)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mopub.nativeads.MoPubCustomEventNative$MoPubStaticNativeAd$1.onImagesCached(MoPubCustomEventNative.java:179)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mopub.nativeads.NativeImageHelper$1.onResponse(NativeImageHelper.java:62)
	10-20 09:44:29.404 12627 12627 W System.err: 	at com.mopub.volley.toolbox.ImageLoader$4.run(ImageLoader.java:474)
	10-20 09:44:29.405 12627 12627 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
	10-20 09:44:29.405 12627 12627 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
	10-20 09:44:29.405 12627 12627 W System.err: 	at android.os.Looper.loop(Looper.java:241)
	10-20 09:44:29.405 12627 12627 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6274)
	10-20 09:44:29.405 12627 12627 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
	10-20 09:44:29.405 12627 12627 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	10-20 09:44:29.405 12627 12627 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
	10-20 09:44:29.419 12627 13052 W FlurryAgent: Flurry  session ended

**Comment by amenk** [comment]
Currently debugging it...

**Comment by amenk** [comment]
I am on release-84 --- seems to come from a new option to purchase ad removal. Maybe a basic "Null" check does ...

**Comment by amenk** [comment]
hm, was not at the recent version of the branch, looks like it was fixed, sorry for the noise
